### ISSUE TITLE
Style\CSS is not applied while converting HTML to PDF.

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#238]
Version: 1.8.27
Original reporter: 

Style\CSS is not applied while converting HTML to PDF.
The following code does not appear as 2px thick orange color border in converted PDF file.

The code is 
       <td Style="border:solid 2px #E87511;">Policy Number</td> 

It seems the attribute 'Style' is not recognized by the HTMLDOC converter.

**Comment by AlanCW** [comment]
Hi Michael,

I'm trying to use htmldoc to convert an html invoice generated by Gnucash into a pdf that I will email my client. I'm using htmldoc version 1.9.2 under KDE Neon (Ubutnu 18).

After exporting from Gnucash, I made a script that makes severe modifications to the html in order to produce a decent-looking (i.e., professional and presentable) document. One of the necessities is to reference an external stylesheet with lots of rules.

I had read too late that htmldoc does not support CSS. So naturally, the invoice does not look right.

Also, it seems that the logo jpg, which appears in the html, does not make it into the pdf.

Any word when CSS will be supported?

Thank you!

**Comment by michaelrsweet** [comment]
@AlanCW I’ve been puttering with a new HTML/CSS library that could form the basis of a new version of HTMLDOC, but I can’t say when that might see the light of day. The library part is being developed separately in the [htmlcss](https://github.com/michaelrsweet/htmlcss) project.
