### ISSUE TITLE
Load fonts at compilation time (feature request)

### ISSUE THREAD

**Issue by RekGRpth** [michaelrsweet/htmldoc#354]
I discovered, that with utf-8 this code
```c
if (_htmlUTF8)
  for (ch = 0; ch < 65536; ch ++)
    if (_htmlGlyphsAll[ch] && !strcmp(_htmlGlyphsAll[ch], glyph))
      _htmlWidthsAll[i][j][ch] = width * 0.001f;
```
is executed more than second!
How about to load font and its metric at compilation time?

**Comment by michaelrsweet** [comment]
We'd need to embed ALL of the font metrics. Will see if I can optimize this instead...

**Comment by michaelrsweet** [comment]
OK, this code kept searching for glyph matches even after a match was found. Breaking in the loop after the first match seems to reduce load times significantly (from 500ms to 200ms on my MacBook Pro) and we get the same output.

[master bec73bb] Optimize the loading of font widths - wasn't stopping on the first match (Issue #354)

**Comment by RekGRpth** [comment]
> We'd need to embed ALL of the font metrics.

Why not? At compilation time You can translate font and its metrics to some binaries. And at execution time You can fastly load these binaries!

**Comment by michaelrsweet** [comment]
The size of the binary files could easily exceed the current text files if I encoded width tables for every character set, which will also have a bigger impact on program startup time (many more pages need to be pulled from disk into memory)

Realistically the current HTMLDOC code needs a major overhaul, something far beyond making major changes to this one small section of code. The changes I did make provide a 2.5x speedup, which IMHO is both significant and useful.

Knowing that the font width loading can be a performance bottleneck, I will make sure to benchmark the new (TrueType) code over in my htmlcss project so that it is as efficient as possible. That code also deals exclusively with Unicode to eliminate extra conditions and branches.

**Comment by RekGRpth** [comment]
How about to change strings to ints at compilation time (for example, export all strings from all files, sort it and put all into one file, then corresponding int for string is string's line number) and at execution time compare ints instead strings?

**Comment by RekGRpth** [comment]
How about to load font metrics only if this font is used?

**Comment by michaelrsweet** [comment]
@RekGRpth The overhead of checking whether the font widths are loaded prior to every measurement might easily exceed the savings of not pre-loading. But I'll do a quick prototype to see if the savings are measurable...

**Comment by RekGRpth** [comment]
Not before every measurement! But only if font is used then load metrics and strore in RAM

**Comment by michaelrsweet** [comment]
Sigh... We don't know that we need to use a font until we do a measurement... But I'll see whether it makes a difference.

**Comment by RekGRpth** [comment]
I was mean variable "fonts_used"

**Comment by michaelrsweet** [comment]
OK, surprisingly when I added this to HTMLDOC and ran performance testing using the users manual and test suite files: 1.9.5 took 1430ms to produce PDFs, master@3992ca7 took 1040ms (with the memory savings and optimized font loader), and master@66d663f took 550ms overall. The biggest win was with UTF-8 text (no surprise) going from 530ms for welcome.md in 1.9.5 to 10ms (!) with Github master.

[master 66d663f] Further optimize font width loading (Issue #354)
