### ISSUE TITLE
Font Origin / License question

### ISSUE THREAD

**Issue by kentfredric** [michaelrsweet/htmldoc#397]
I've stumbled down a rabbit hole of sorts.

I've been trying to find sources of Helvetica.afm (mostly just triggered by some obscure test), and in my searches for vendored things, htmldoc turned up.

The Helvetica.afm files in git raise a few questions for me, (some potentially with some legal stuff that we maybe should be handling downstream), particularly as it appears that Helvetica is considered "proprietary software" and requires a paid license from Lineotype: https://www.fonts.com/font/linotype/helvetica

- Where did you/how did you obtain these fonts? 
- Is "Helvetica" actually Helvetica or some other font renamed?    https://github.com/michaelrsweet/htmldoc/blob/b005d420deb1c928a93ee39299ed4760c96030ea/fonts/Helvetica.afm#L5-L7
- If the latter, what from
- If it is Helvetica, than how can it be "GPL" ?
https://github.com/michaelrsweet/htmldoc/blob/b005d420deb1c928a93ee39299ed4760c96030ea/fonts/Helvetica.afm#L4
- Where is the "Copying" file for the fonts? ( https://github.com/michaelrsweet/htmldoc/tree/master/fonts ), I mean, one might assume its the same as the top level COPYING, but just the excerpted line doesn't clarify which GPL version its referring to, so it might be a *different* file that wasn't copied :/ 

And I don't see any good evidence that URW++ created a font called "Helvetica":
https://github.com/michaelrsweet/htmldoc/blob/b005d420deb1c928a93ee39299ed4760c96030ea/fonts/Helvetica.afm#L14

But I *do* know "Nimbus Sans L" is a thing, and was a Helvetica-like font by URW++ that is GPLy, but maybe *AGPL-3*! :) 

https://github.com/ArtifexSoftware/urw-base35-fonts/blob/master/fonts/COPYING 

Apologies if this all requires long unactivated memory cells :)

**Comment by michaelrsweet** [comment]
All of the base fonts are the original URW fonts which were licensed under GPLv2. I just renamed them to their equivalent font names since I didn’t want to bother with a Ghostscript-style mapping table.

FWIW, current Ghostscript comes with a slightly newer version of these fonts that now carries a GPLv3 license, even though the last copyright date on those fonts is several years before the GPLv3 was published. This unfortunately causes a lot of confusion as well.
