### ISSUE TITLE
Automatically display print dialog when PDF opens

### ISSUE THREAD

**Issue by BartVanderDonck** [michaelrsweet/htmldoc#404]
Is there a way to automatically display the print dialog when opening a PDF file ? I've been trying to use Named Action but with no success. Basically I was regexp-ing the existing htmldoc header from:

  1 0 obj<</Producer(htmldoc 1.8...>>endobj
  2 0 obj<</Type/Encoding/Differ...>>endobj
  3 0 obj<</Length1 1591/Length2...>>stream

to something like:

  1 0 obj
  <</Type /Catalog /Pages 3 0 R
  /OpenAction  9 0 R
  /Metadata 10 0 R
  >>
  endobj

  9 0 obj
  <</S/Named
  /Type/Action
  /N/Print>>endobj

But with this and other variants I always get an I/O error. My thoughts:
- Direcly regexp-ing PDF-source is not very elegant
- Background: the user already clicked "Print PDF" in the browser
- In an ideal world I would call htmldoc with PRINTDIALOG = true

Thanks

**Comment by michaelrsweet** [comment]
@BartVanderDonck I don't believe there is a way to do this consistently (i.e. maybe for Acrobat Reader but not for Edge, Firefox, Chrome, Safari, etc.) but I'll see if there is something I can do.

What you might need to do is embed the PDF in a web page so that you can bring up the print dialog via Javascript... But that will depend on the PDF being handled by the browser...

**Comment by michaelrsweet** [comment]
Did a little digging and it looks like JavaScript is the only solution:

```
<a href="example.PDF" onclick="w = window.open(this.href);w.print();return false;">Print example.PDF</a>
```
