### ISSUE TITLE
configure fails if /usr/lib/pkgconfig/libtasn1.pc not installed for 1.9.12 build

### ISSUE THREAD

**Issue by BrianInglis** [michaelrsweet/htmldoc#450]
If `/usr/lib/pkgconfig/libtasn1.pc` is not installed `configure` of 1.9.12 build fails under *Cygwin*. 
Document in `INSTALL.md` that the appropriate libtasn1 dev/devel package should be installed, 
or modify or remove check for this requirement if not used directly (by GNUTLS?) for TLS. 
Environment current *Cygwin* `cygport` build using standard GNU toolchain and required devel libraries.

**Comment by michaelrsweet** [comment]
@BrianInglis I checked and the configure script doesn't look for libtasn1 directly, so it must be coming from a GNU TLS dependency. Nothing I can really do about it, and since GNU TLS depends on it I would expect any packages to carry that dependency forward (doesn't sound like Cygwin is doing so...)

**Comment by BrianInglis** [comment]
You're right, the [`GNUTLS`](https://gitlab.com/gnutls/gnutls/-/blob/master/README.md) dependency list is now ridiculous, and what they deem optional seems not to be by `autoconf` rules.
