### ISSUE TITLE
Broken links after version 1.9.3

### ISSUE THREAD

**Issue by prichterich** [michaelrsweet/htmldoc#514]
I have a project with about 40 html files, many of them with internal anchors and links to such internal anchors. An example: 
`<a href="Project3.htm#Create">New Project</a>`
In the source file, the anchor is:
`<h2><a name="Create"></a>Creating New Projects</h2>`
With version 1.9.3, these links are correctly resolved in the PDF file. But with newer versions, all links to an internal anchor are broken. When hovering over the link, is shows as:
` file:///Users/Shared/.../Project3.htm%23Create`

I'd prefer to use the current version since it contains relevant bug fixes, but the broken links to internal anchors prevent that. This issue was introduced shortly after 1.9.3, possibly in 1.9.4. I have tried a number variations of defining the <a> elements, but nothing worked.

**Comment by prichterich** [comment]
A ZIP archive with a simple example is attached. It includes the PDF file generated by 1.9.3, where the link works, and the PDF file from 1.9.17, where it is broken.

On my M2 Mac running macOS13, the GUI versions of html doc are broken. 1.9.3 pops up an empty window, 1.9.17 does nothing.
I don’t care since I use scripts, anyway, but thought I’d mention it.


￼

**Comment by michaelrsweet** [comment]
@prichterich The ZIP file got stripped...

**Comment by prichterich** [comment]
Thought it would get through the email notification. Attaching it here instead:
[htmldoc_link_bug.zip](https://github.com/michaelrsweet/htmldoc/files/12841272/htmldoc_link_bug.zip)

**Comment by jmdoudoux** [comment]
I've been using the HTMLDOC for decades to generate a PDF file currently of over 4200 pages from 135 HTML files.
I'd like to take this opportunity to thank you very much for this wonderful tool.

For a long time, I have been using version 1.8.24 because of issue #505.
Since its correction, I've been using version 1.9.17. 

And I also have the issue of broken links describe above.

I was able to apply a workaround because I have a tool that pre-processes the HTML files before they are processed by HTMLDOC.

For this particular problem, I had to replace the href="file.htm#anchor" (which works very well in 1.8.24) by simply "#anchor" (so that it works now in 1.9.17).

Obviously this workaround works because all my anchors are unique in all HTML source files.

I hope this helps for the investigations.

**Comment by prichterich** [comment]
Thanks for describing the workaround. Unfortunately, our links are not unique, so this would require a substantial amount of editing. It would also complicate the build process by adding a pre-processing step, since we also need the help to work with links that include the file names.

**Comment by michaelrsweet** [comment]
Fixed here:

[master 4620dee] Fix file-based links in PDF output (Issue #514)

The fix adds a link of the form "filename#anchor" in addition to adding or updating the shortened "#anchor" link. The code will still have issues with using "#anchor" links when the anchor string is not unique in the collection of HTML files/URLs but I'm not sure I have enough context in HTMLDOC to handle that at the point the link is rendered...
